export const icons = {
  eye: require("../assets/icons/eye.png"),
  eye_hide: require("../assets/icons/eye-hide.png"),
  drawer: require("../assets/icons/drawer.png"),
  home: require("../assets/icons/home.png"),
  faq: require("../assets/icons/faq.png"),
  products: require("../assets/icons/products.png"),
  notification: require("../assets/icons/notification.png"),
  dot_menu: require("../assets/icons/dot_menu.png"),
  search: require("../assets/icons/search.png"),
  logout: require("../assets/icons/logout.png"),
  profile: require("../assets/icons/profile.png"),
  plus: require("../assets/icons/plus.png"),
  edit: require("../assets/icons/edit.png"),
  back: require("../assets/icons/back.png"),
  right_arrow: require("../assets/icons/right-arrow.png"),
  downloads: require("../assets/icons/downloads.png"),
  camera: require("../assets/icons/camera.png"),
  capture: require("../assets/icons/capture.png"),
  flip_camera: require("../assets/icons/flip_camera.png"),
  gallery: require("../assets/icons/gallery.png"),
  grid: require("../assets/icons/grid.png"),
  close: require("../assets/icons/close.png"),
  pencil: require("../assets/icons/pencil.png"),
  calendar: require("../assets/icons/calendar.png"),
};
